In [1]:
import numpy as np

Arraay creation and conversion

In [2]:
arr1 = np.array([1,2,3])
print("array:", arr1)

array: [1 2 3]


In [3]:
print(arr1.size)

3


In [9]:
print(arr1.shape)

(3,)


In [3]:
arr2 = np.array([[1,2],[2,1],[3,4]])
print(arr2.size) #3rows and 2columns

6


In [4]:
arr3 = np.array([[1,2], [2,1], [3,4]])
arr4 = np.array([[5,6], [7,8], [9,0]])
arr34_add = arr3+arr4
print("array addition:", arr34_add)
arr34_mult = arr3*arr4
print("array multiplication:", arr34_mult)
arr5 = arr4%arr3
print("array modulo:",arr5)

array addition: [[ 6  8]
 [ 9  9]
 [12  4]]
array multiplication: [[ 5 12]
 [14  8]
 [27  0]]
array modulo: [[0 0]
 [1 0]
 [0 0]]


[[0 0]
 [1 0]
 [0 0]]


In [25]:
arr_sum = np.sum([arr3, arr4])
print(arr_sum)

48


In [28]:
b = np.asarray((4,5,6))
print(b)

[4 5 6]


In [29]:
c = np.arange(0, 10, 2)
print(c)

[0 2 4 6 8]


In [35]:
d = np.linspace(0,10,3)
print(d)

[ 0.  5. 10.]


In [37]:
e = np.logspace(0,2,5)
print(e)

[  1.           3.16227766  10.          31.6227766  100.        ]


In [39]:
f = np.zeros((2,3))
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]


In [47]:
g = np.ones((2, 3), dtype=int)
print(g)

[[1 1 1]
 [1 1 1]]


In [46]:
h = np.empty((2,2))
print(h)

[[ 0.          3.33333333]
 [ 6.66666667 10.        ]]


In [49]:
i = np.full((2,2),7)
print(i)

[[7 7]
 [7 7]]


In [55]:
j = np.eye(3,4)
print(j)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [54]:
k = np.identity(3)  #identity matrix of order 3
print(k)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
